

#
# User configuration sourced by interactive shells
#

# Define zim location 
(( ! ${+ZIM_DATA_DIR} )) && export ZIM_DATA_DIR="${XDG_DATA_HOME:-"${HOME}/.local/share"}/zim"

# Source zim
if [[ -s "${ZIM_DATA_DIR}/init.zsh" ]]; then
  source "${ZIM_DATA_DIR}/init.zsh"
fi

